version: '3'

services:
  db:
    container_name: database
    image: postgres:12
    hostname: database
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: boostersnews
      POSTGRES_USER: boosterdev
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5442:5432

  app:
    container_name: backend-main
    hostname: app
    restart: always
    build:
      context: ""
      dockerfile: .cicd/build/Dockerfile
    environment:
      ENV: dev
      POSTGRES_URL: postgres://boosterdev:mysecretpassword@database:5432/boostersnews
      HTTP_HOST_ADDR: :8080
    ports:
      - 48011:8080
    depends_on:
      - db

