/*
 * Boosters news server API
 *
 * Implement API test server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Post struct {

	// Post ID
	Id int64 `json:"id" binding:"required"`

	// created at timestamp
	CreatedAt int64 `json:"created_at" binding:"required"`

	// created at timestamp
	UpdatedAt int64 `json:"updated_at,omitempty"`

	// post title
	Title string `json:"title" binding:"required"`

	// post content, can be empty on post list
	Content string `json:"content" binding:"required"`
}
