/*
 * Boosters news server API
 *
 * Implement API test server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BadRequestSchema struct {

	// Request status.
	Status string `json:"status"`

	// error description
	Message string `json:"message,omitempty"`

	Data BadRequestSchemaData `json:"data,omitempty"`
}
