/*
 * Boosters news server API
 *
 * Implement API test server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Post struct {

	// Recipe ID
	Id int32 `json:"id,omitempty"`

	// Main Image URL
	ImageUrl string `json:"image_url,omitempty"`

	// created at timestamp
	CreatedAt int64 `json:"created_at,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`

	// blog title
	Title string `json:"title,omitempty"`

	// blog heading
	Heading string `json:"heading,omitempty"`

	// blog content, can be empty on blogs list
	Content string `json:"content,omitempty"`
}
