/*
 * Boosters news server API
 *
 * Implement API test server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BadRequestSchemaData - Data
type BadRequestSchemaData struct {

	// error object
	Errors map[string]interface{} `json:"errors,omitempty"`
}
